# Change these first
owner: TrialOrg321 # Your GitHub organization or username, where this repository lives
repo: homelab-monitor # The name of this repository

sites:
  - name: Portfolio 
    url: https://adityaap.tech
  - name: Authentik 
    url: https://auth.adityaap.tech
  - name: Owncloud 
    url: https://owncloud.adityaap.tech
  - name: Immich 
    url: https://immich.adityaap.tech
  - name: Jellyfin 
    url: https://jellyfin.adityaap.tech
  - name: Minio
    url: https://minio-console.adityaap.tech


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.adityaap.tech 
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Aditya's Homelab
  introTitle: ""
  introMessage: Track uptime for my personal homelab
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
